name: teste Environments

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: $GITHUB_REF
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo ${{ secrets.OLA }}
        echo ${{ vars.OUTRO }}
        env | sort
